#%RAML 0.8
---
title: CCP Subscriber API
version: 1
baseUri: http://server/api/v{version}/ccp/customer
#baseUri: http://mocksvc.mulesoft.com/mocks/2bf9c5ce-6960-4f14-ae70-03de63eaa085/api/v{version}/ccp/customer
/ccp_subscriber:
  displayName: ccp_subscriber
  post:
    description: Submit ccp_subscriber request
    body:
      application/json:
        schema: !include schema/input.json
        example: !include schema/example.json
    responses:
      200:
        body:
          application/json:
            
            example: !include schema/response_example.json
             
